on:
  push:
    tags:
      - "v*"

jobs:
  homebrew:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: mcp-server-zai-zread
          push-to: katopz/extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
